config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'search/:role', to: 'home#search', as: 'search'
  post 'home', to: 'home#sign_in', as: 'sign_in'
  delete '/', to: 'home#sign_out', as: 'sign_out'

  get 'people(/:id)', to: 'people#show', as: 'people'

  resources :appointments
  resources :notes

  mount SqlProbe::Engine => '/sql_probe' if defined? SqlProbe
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# Something to attend.
# Only needs a title at creation. Other attributes can be
# set later as details emerge.
class Appointment < ApplicationRecord
  has_many :attendants
  has_many :notes, as: :notable
  has_many :people, through: :attendants

  def names
    attendants.map { |attendant| attendant.person.name }.sort
  end

  def emails
    attendants.map { |attendant| attendant.person.email }.sort
  end
end

app/models/attendant.rb
class Attendant < ApplicationRecord
  belongs_to :appointment
  belongs_to :person
end

app/models/note.rb
# Attach notes to anything via notable.
# A note must have a writer
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
  belongs_to :author, class_name: 'Person'
end

app/models/person.rb
# A person has a name  and email.
# Fake it unless you want to catch hipaatitis.
class Person < ApplicationRecord
  has_many :notes, as: :notable
  has_many :authored_notes, foreign_key: :author_id, class_name: 'Note'
  has_and_belongs_to_many :roles
  has_many :attendants
  has_many :appointments, through: :attendants

  def to_s
    "#{name} <#{email}>"
  end

  def role?(title)
    roles.detect { |role| title == role.title }
  end

  def role_title
    roles[0].try(:title)
  end

  def next_appointment
    appointments.detect { |d| d.when >= Time.current }
  end

  def next_appointment_time
    next_appointment.try(:when)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SqlProbe::RequestListener if defined? SqlProbe
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= Person.find(current_user_id) if current_user_id
  end
  helper_method :current_user

  def current_user_id
    session[:current_user_id]
  end
  helper_method :current_user_id
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, except: :index

  def index
    @month = (params[:month] ? Date.parse(params[:month]) : Date.current).beginning_of_month

    @appointments = Appointment.where(when: @month.beginning_of_month..@month.end_of_month)
  end

  def show

  end

  private

  def find_appointment
    @appointment = Appointment.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user_id
      redirect_to people_path
      return
    end
    @counts = Person.joins(:roles).group('roles.title').count
  end

  def sign_in
    found = Person.find_by!(params[:person].permit(:email))
    session[:current_user_id] = found.id
    redirect_to people_path
  end

  def sign_out
    session.delete(:current_user_id)
    redirect_to action: 'index'
  end

  def search
    @role = params[:role]
    @people = finder
  end

  private

  def finder
    Person
      .joins(:roles)
      .where(roles: { title: params[:role] })
      .order(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = current_user.notes
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_person, except: :index

  def show
    @month = (params[:month] ? Date.parse(params[:month]) : Date.current).beginning_of_month
  end

  private

  def find_person
    @person = Person.find(params[:id] || current_user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def select_people(people)
    collection_select(:person, :id, people, :id, :to_s, {}, class: 'form-control')
  end

  def select_people_sign_in(people)
    collection_select(:person, :email, people, :email, :to_s, {}, class: 'form-control')
  end

  def attendant_links(owner, appointment)
    appointment.attendants
      .reject { |r| r.person == owner }
      .map { |attendant| link_to(attendant.person.to_s, people_path(id: attendant.person_id)) }
      .join(',').html_safe + ' and you'.html_safe
  end

  def link_to_appointment(appointment, **html)
    link_to(appointment.when.strftime("#{appointment.title} @ %-I:%m %p"), appointment_path(appointment), **html)
  end
end

app/helpers/calendar.rb
# static functions to build interesting calendars
module Calendar
  module_function

  def beginning_of_calendar(date = Date.current)
    begin_date = date.beginning_of_month.beginning_of_week
    begin_date.month == date.month ? (begin_date + 1.week) : begin_date
  end

  def end_of_calendar(date = Date.current)
    end_date = date.end_of_month.end_of_week
    end_date.month == date.month ? end_date + 1.week : end_date
  end

  def days_of_week(format: '%A')
    date = Date.current.beginning_of_week
    (date..(date + 6.days)).map { |m| m.strftime(format) }
  end

  def group_by_week(range)
    range.group_by{|g| (g + 1.day).cweek}
  end

  def display_long(time)
    time.try(:strftime, "%A, %B #{time.day.ordinalize}, %Y %I:%m %p")
  end
end

app/views/appointments/_calendar.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="btn-group pull-right" role="group" aria-label="calendar navigation">
      <%= link_to '<< Previous', appointments_path(month: @month - 1.month), class: 'btn btn-default btn-xs' %>
      <%= link_to 'Current Month', appointments_path, class: 'btn btn-default btn-xs' %>
      <%= link_to 'Next >>', appointments_path(month: @month + 1.month), class: 'btn btn-default btn-xs' %>
    </div>
    <h3 class="panel-title">
      All appointments in <%= @month.strftime('%B, %Y') %>
      <small>(count: <%= pluralize @appointments.size, 'appointment' %>)</small>
    </h3>
  </div>
  <div class="table-responsive">
    <%= render 'shared/appointments', date: @month, appointments: @appointments %>
  </div>
</div>

app/views/appointments/index.erb
<%= render 'calendar' %>

app/views/appointments/show.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @appointment.title %></h3>
  </div>
  <div class="panel-body">
    <%= render 'shared/long_time', date: @appointment.when %>
    <hr/>
    <p> <%= @appointment.body %> </p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Attendants</h3>
      </div>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Email</th>
        </tr>
        <% @appointment.people.each do |person| %>
          <tr>
            <td><%= person.name %></td>
            <td>
              <%= person.email %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Notes</h3>
      </div>
      <%= render 'shared/notes', notes: @appointment.notes %>
    </div>
  </div>
</div>

app/views/home/index.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1>Hipaatitis
      <%= image_tag 'logo.svg', alt: 'Hipaatitis', class: 'header-img' %>
    </h1>
    <p>
    Are you sick of privacy?<br/>
    Do you want to be free from the shadows?<br/>
    This CRM has you <em>un</em>covered.<br/>
    Make all your appointments out in the open!
    </p>
    <p>
      <%= link_to "I'm a Doctor", search_url(role: 'Doctor'), class: 'btn btn-primary btn-lg', role: 'button' %>
      <%= link_to "I'm a Patient", search_url(role: 'Patient'), class: 'btn btn-primary btn-lg', role: 'button' %>
    </p>
    <p>We currently have
    <%= pluralize @counts['Doctor'], 'doctor' %> and
    <%= pluralize @counts['Patient'], 'patient' %> registered!
    </p>
  </div>
</div>
<p class="text-center smaller">
Disclaimer: This is not a real product. If you believe it should be, please send money <a href="#">here</a>
</p>

app/views/home/search.erb
<div class="jumbotron text-center">
  <%= render 'layouts/person_icons', role: params[:role] %>
  <h1>Which <b><%= params[:role].downcase %></b> are you?</h1>

  <hr/>
  <%= form_tag(sign_in_path) do %>
    <div class="form-group">
      <label for="exampleInputEmail1">Select your identity below. If you can't find yourself. It's okay. Pretend to be someone else.</label>
      <%= select_people_sign_in(@people) %>
    </div>
    <button type="submit" class="btn btn-default btn-primary btn-lg">Sign In</button>
  <% end %>
</div>

app/views/layouts/_bottom.erb
<footer class="footer container-fluid text-right">
  <div class="attribution">Medical icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0</a></div>
  <div class="attribution">Emoji provided free by <a href="http://emojione.com">EmojiOne</a></div>
</footer>

app/views/layouts/_ga.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-97616584-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_person_icons.erb
<% if role == 'Doctor' %>
  <%= image_tag(['medical-kit.svg', 'syringe.svg'].sample, class: 'person-icon') %>
<% elsif role == 'Patient' %>
  <%= image_tag(['sick-1f912.svg', 'sick-1f915.svg'].sample, class: 'person-icon') %>
<% end %>

app/views/layouts/_top.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Hipaatitis<%= image_tag 'logo.svg', alt: 'Hipaatitis' %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if params[:controller] == 'people' and params[:id].blank? %>><%= link_to "Welcome, #{current_user.name}", people_path %></li>
        <li <%= 'class=active' if params[:controller] == 'notes' %>><%= link_to 'Notes', notes_path  %></li>
        <li <%= 'class=active' if params[:controller] == 'appointments' and params[:id].blank? %>><%= link_to 'All Appointments', appointments_path %></li>
        <li><%= link_to 'Probe*', '/sql_probe', target: 'probe' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign Out', sign_out_path, method: 'delete' %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hipaatitis</title>
    <%= csrf_meta_tags %>
    <%# <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
    </style>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'layouts/top' if current_user_id %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>
    <%= render 'layouts/ga' %>
    <%= render 'layouts/bottom' %>
  </body>
</html>

app/views/notes/index.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Notes</h3>
  </div>
  <%= render 'shared/notes', notes: @notes %>
</div>

app/views/people/_appointment_calendar.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="btn-group pull-right" role="group" aria-label="calendar navigation">
      <%= link_to '<< Previous', people_path(id: params[:id], month: @month - 1.month), class: 'btn btn-default btn-xs' %>
      <%= link_to 'Current Month', people_path(id: params[:id]), class: 'btn btn-default btn-xs' %>
      <%= link_to 'Next >>', people_path(id: params[:id], month: @month + 1.month), class: 'btn btn-default btn-xs' %>
    </div>
    <h3 class="panel-title">
      <%= @person == current_user ? "Your" : "#{@person.name}'s" %>
      appointments in <%= @month.strftime('%B, %Y') %>
      <small>(<%= pluralize @person.appointments.count, 'appointment' %> in the future.)</small>
    </h3>
  </div>
  <div class="table-responsive">
    <%= render 'shared/appointments', date: @month, appointments: @person.appointments %>
  </div>
</div>

app/views/people/_appointment_list.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="btn-group pull-right" role="group" aria-label="calendar navigation">
      <%= link_to('Show Next Apppointment', people_path(id: params[:id], month: @person.next_appointment_time), class: 'btn btn-default btn-xs') if @person.next_appointment_time %>
    </div>
    <h3 class="panel-title">Upcoming Appointments</h3>
  </div>
  <table class="table table-condensed">
    <th>When</th>
    <th>What</th>
    <th>Attendants</th>
    <% @person.appointments.order(:when).each do |appointment| %>
      <tr>
        <td class="text-nowrap">
          <%= render 'shared/long_time', date: appointment.when %>
        </td>
        <td><b><%= appointment.title %></b><p><%= appointment.body %></p>
        </td>
        <td>
          <%= attendant_links(@person, appointment) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/people/_note_list.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Notes</h3>
  </div>
  <%= render 'shared/notes', notes: @notes %>
</div>

app/views/people/show.erb
<%= render 'appointment_calendar' %>
<%= render 'appointment_list' %>

app/views/shared/_appointments.erb
<% date || raise(ArgumentError, ':date is required!') %>
<% appointments || raise(ArgumentError, ':appointments are required!') %>

<% by_date = appointments.group_by{|g| g.when.to_date} %>
<% first_date = Calendar.beginning_of_calendar(date) %>
<% last_date = Calendar.end_of_calendar(date) %>

<table class="table table-bordered calendar">
  <% Calendar.days_of_week.each do |day| %>
    <th class="text-center"><%= day %></th>
  <% end %>
  <% Calendar.group_by_week(first_date..last_date).each do |week, days| %>
    <tr>
      <% days.each do |day| %>
        <td class="cal-td <%= date.month != day.month ? 'cal-off' : '' %>">
          <div class="cal-day"><%= day.day %></div>
          <% by_date[day].try(:each) do |appointment| %>
            <div class="cal-appt"><%= link_to_appointment(appointment, class: 'btn btn-xs btn-primary') %></div>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_long_time.erb
<% date || raise(ArgumentError, ':date is required!') %>
<% if date %>
<%= date.strftime("%A, %B #{date.day.ordinalize}, %Y") %><br/>
<%= date.strftime("@ %-I:%m %p") %><br/>
<%= time_ago_in_words date %> from now
<% end %>

app/views/shared/_notes.erb
<% notes || raise(ArgumentError, ':notes are required!') %>

<table class="table table-bordered calendar">
  <tr>
    <th>From</th>
    <th>Note</th>
    <th style="width: 10em">Date</th>
  </tr>
  <% notes.each do |note| %>
    <tr>
      <td><%= note.author.name %></td>
      <td>
        <b><%= note.title %></b><br/>
        <%= note.body %>
      </td>
      <td><%= time_ago_in_words note.updated_at %> ago </td>
    </tr>
  <% end %>
</table>